language: php
php:
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6

# Cache folder, you can delete cache from Travis CI web interface
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

addons:
  sauce_connect:
    username: "testqwe123"
    access_key: "68d89191-ae15-40b1-aa5a-a11b2b6d07f4"

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

# Install packages those will be required during build
install:
  - composer install --no-interaction

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

script:
  - ./vendor/bin/codecept run
