<? append_script('js/orders.js'); ?>
<? /** @var array $data */ ?>
<div class="row">
    <div class="col-md-6 col-lg-offset-3">
        <form>
            <input type="hidden" name="token" value="<?=$data['token']?>">
            <div class="form-group">
                <label for="inputTitle"><?=_('Name')?></label>
                <input type="text" name="title" class="form-control" id="inputTitle">
            </div>
            <div class="form-group">
                <label for="inputDesc"><?=_('Description')?></label>
                <textarea name="desc" class="form-control" id="inputDesc"></textarea>
            </div>
            <div class="form-group">
                <label for="inputCost"><?=_('Price')?></label>
                <input name="cost" type="text" class="form-control" id="inputCost">
            </div>
            <a onclick="orders.saveOrder(this)" class="btn btn-primary"><?=_('Add Order')?></a>
            <div class="error-message" style="display: none;"></div>
        </form>
    </div>
</div>