<? /** @var array $data */ ?>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th><?=_('Name')?></th>
            <th><?=_('Description')?></th>
            <th><?=_('Price')?></th>
            <th><?=_('Customer')?></th>
            <th><?=_('Date of completion')?></th>
        </tr>
        </thead>
        <tbody>
        <? if (!empty($data['orders'])): ?>
            <? foreach ($data['orders'] as $row): ?>
                <tr>
                    <td><?=$row['title']?></td>
                    <td><?=nl2br($row['description'])?></td>
                    <td><?=$row['cost']?></td>
                    <td><?=$row['customer_login']?></td>
                    <td><?=date('Y-m-d H:i:s', $row['completed'])?></td>
                </tr>
            <? endforeach; ?>
        <? else: ?>
            <tr><td colspan="5"><?=_('You have no any completed orders')?></td></tr>
        <? endif; ?>
        </tbody>
    </table>
</div>