<? /** @var array $data */ ?>
<? append_script('js/orders.js'); ?>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th><?=_('Name')?></th>
            <th><?=_('Description')?></th>
            <th><?=_('Price')?></th>
            <th><?=_('Customer')?></th>
            <th><?=_('Date of completion')?></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <? if (!empty($data['orders'])): ?>
            <? foreach ($data['orders'] as $row): ?>
                <tr>
                    <td><?=$row['title']?></td>
                    <td><?=nl2br($row['description'])?></td>
                    <td><?=$row['cost']?></td>
                    <td><?=$row['customer_login']?></td>
                    <td><?=date('Y-m-d H:i:s', $row['inserted'])?></td>
                    <td style="text-align: center;">
                        <a href="javascript:" onclick="orders.completeOrder(this, <?=$row['order_id']?>, '<?=$data['token']?>')" class="btn btn-primary">
                            <?=_('Complete order')?>
                        </a>
                    </td>
                </tr>
            <? endforeach; ?>
        <? else: ?>
            <tr><td colspan="6"><?=_('No new orders')?></td></tr>
        <? endif; ?>
        </tbody>
    </table>
</div>