<? global $user; ?>
<? /** @var array $data */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=$data['head_title']?></title>

    <link rel="icon" href="<?=get_static_url('images/favicon.ico')?>">

    <link href="<?=get_static_url('css/bootstrap.min.css')?>" rel="stylesheet">
    <link href="<?=get_static_url('css/styles.css')?>" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="<?=get_static_url('js/jquery-2.1.3.min.js')?>"></script>
    <script src="<?=get_static_url('js/bootstrap.min.js')?>"></script>
    <script src="<?=get_static_url('js/base.js')?>"></script>

    <? global $head_css, $head_scripts; ?>
    <? foreach ($head_css as $url): ?>
        <link href="<?=$url?>" rel="stylesheet">
    <? endforeach; ?>
    <? foreach ($head_scripts as $url): ?>
        <script src="<?=$url?>"></script>
    <? endforeach; ?>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <? if ($user): ?>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <? endif; ?>
            <a class="navbar-brand" href="/"><?=_('Заказы')?></a>
        </div>
        <? if ($user): ?>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <? if ($user['role'] == ROLE_CUSTOMER): ?>
                        <li><a href="/customer/"><?=_('Мои заказы')?></a></li>
                        <li><a href="/customer/add/"><?=_('Добавить заказ')?></a></li>
                    <? elseif ($user['role'] == ROLE_EXECUTOR): ?>
                        <li><a href="/executor/"><?=_('Список заказов')?></a></li>
                        <li><a href="/executor/completed/"><?=_('Выполненные заказы')?></a></li>
                    <? endif; ?>
                    <li><a href="javascript:" onclick="base.signOut()"><?=_('Выйти')?></a></li>
                    <? if ($user['role'] == ROLE_EXECUTOR): ?>
                        <li><div id="user-balance"><?=_('Баланс: ')?><span><?=$user['balance']?></span></div></li>
                    <? endif; ?>
                </ul>
            </div><!-- /.nav-collapse -->
        <? endif; ?>
    </div><!-- /.container -->
</nav>
<div class="container">
    <? if (isset($data['page_title'])): ?>
        <div class="page-header" style="border-color: #ccc; margin-top: -20px;">
            <h1><?=$data['page_title']?></h1>
        </div>
    <? endif; ?>
    <?=$data['content_html']?>
</div> <!-- /container -->
<script>
    $(function() {
        $('input, textarea').keypress(function (e) {
            if (e.which == 13) {
                $(this).parents('form').find('a.btn').trigger('click');
            }
        });
    });
</script>
</body>
</html>